services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    # depends_on:
    #   - db
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - RAILS_ENV=production
    command: rails server --binding=0.0.0.0

# Database for developer setup is sqlite3
  # This is a try at configuring for postgresql
  # db:
  #   container_name: kbc-db
  #   environment:
  #     - POSTGRES_PASSWORD=rootpass
  #   image: postgres:14.17
  #   networks:
  #     - kbc-net
  #   ports:
  #     -
  #   volumes:
  #     - ${PWD}/storage/postgresql.conf:/etc/postgresql/postgresql.conf
  #     - ./storage/db_data:/var/lib/postgresql/data
  #   command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
