# Keep this in sync with .ruby-version.
FROM ruby:3.4.8

WORKDIR /usr/src/app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git pkg-config libpq-dev && \
    rm -rf /var/lib/apt/lists/*

COPY Gemfile* .
RUN bundle install

COPY . .

ENV RAILS_ENV=development
EXPOSE 3000

ENTRYPOINT ["/usr/src/app/bin/docker-entrypoint"]
CMD ["./bin/rails", "server", "--binding=0.0.0.0", "--port=3000"]
