FROM ruby:3.4

WORKDIR /usr/src/app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git pkg-config libpq-dev && \
    rm -rf /var/lib/apt/lists/*

COPY Gemfile* .
RUN bundle install

COPY . .

# Expose the port the app runs on
EXPOSE 3000
ENV RAILS_ENV=development

ENTRYPOINT ["/usr/src/app/bin/docker-entrypoint"]
CMD ["./bin/rails", "server", "--binding=0.0.0.0", "--port=3000"]
